language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --dev --prefer-source
  - bash < <(curl -s https://raw.github.com/colinmollenhour/modman/master/modman-installer)
  - curl https://gordonlesti.com/magento-1-9-0-1.tar.gz | tar xz

before_script:
  - mysql -e 'create database `magento-1-9-0-1`;'
  - mysql -utravis magento-1-9-0-1 < magento-1-9-0-1/magento-1-9-0-1.sql

script:
  - php bin/phpcs --standard=Zend -n src/ tests/
  - php bin/phpmd src/,tests/  text codesize,design,unusedcode
