language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - curl https://gordonlesti.com/magento-1-9-0-1.tar.gz | tar xz
  - mv magento-1-9-0-1 magento
  - cd magento
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
  - cd ..

before_script:
  - mysql -e 'create database `magento-1-9-0-1`;'
  - mysql -utravis magento-1-9-0-1 < magento/var/test.sql
  - cd magento
  - ./modman link ./../../Lesti_Fpc
  - ./modman clone https://github.com/EcomDev/EcomDev_PHPUnit.git
  - cd ..

script:
  - cd magento
  - phpunit
