language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install --dev --prefer-source
  - curl https://gordonlesti.com/magento-1-9-0-1.tar.gz | tar xz
  - mv magento-1-9-0-1 magento
  - cd magento
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
  - cd ..

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `magento-1-9-0-1`;'
  - mysql -utravis magento-1-9-0-1 < magento/var/magento-1-9-0-1.sql
  - mysql -e 'create database `magento-1-9-0-1-test`;'
  - mysql -utravis magento-1-9-0-1-test < magento/var/magento-1-9-0-1-test.sql
  - cd magento
  - ./modman link ./../../Lesti_Fpc
  - ./modman clone https://github.com/EcomDev/EcomDev_PHPUnit.git
  - cd ..

script:
  - php vendor/bin/phpcs --standard=Zend app/
  - php vendor/bin/phpmd app/ text codesize,design,unusedcode
  - cd magento && php ../vendor/bin/phpunit --coverage-clover ../build/logs/clover.xml && cd ..

after_script:
  - php vendor/bin/coveralls
